### PR TITLE
refactor/feat rewrite action and add new commands

### LINKED ISSUE #240: Feature: Add `/assign-previous-commenter`
### Type of feature

💡 Feature

### Current behavior

Contributor posts texts, because they is not aware of `/assign-me`:

image

There is no possiblity to comment something to have this magic of assignment (and unassignent aftter a timeout) working.

### Suggested solution

Add `/assign-previous-commenter` which triggers the assignment of the previous (!) comment.

Advanced version could be `/assign {url to issue comment}`

Example: 

    /assign https://github.com/JabRef/jabref/issues/10418#issuecomment-2401128647

This would then assign the poster of that comment to the current issue.

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### LINKED ISSUE #241: Feature: Support `/unassign-me` and `/unassign-previous-commenter`
### Type of feature

💡 Feature

### Current behavior

Currently, a commenter can assign themselves, but not unassign.

### Suggested solution

Offer `/unassign-me` for a self-unassignment and `/unasign-previous-commenter` to unassign the previous commenter. The latter is the oppostite function of the feature wished at https://github.com/takanome-dev/assign-issue-action/issues/240.

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### LINKED ISSUE #244: Feature: `unassigned_comment`
### Type of feature

💡 Feature

### Current behavior

A contributor seems to be automatically unassigned. It would be good if some text is posted.

### Suggested solution

see above.

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

### LINKED ISSUE #246: Feature: Support free-text assignment
### Type of feature

💡 Feature

### Current behavior

Students comment with

> Hello, could you please assign this issue to me? Keen to have a go.

> Hello, I am here to do a university assignment where I attempt to solve issues in open source projects! I would like to work on this issue, and am wondering if it is still available to do.

> Hi [...], my and my group members hope to contribute to this issue. Thx!

> Hi, I was wondering if this issue still needs to be worked on. If so, I would be happy to pick it up!

> I have read through this issue and was wondering if it is still available to take on. 

> Hi! May I work on this issue? I'm new here, thank you!

> Hey! May I work on this issue? thank you!

> I want to take this issue.

or other texts.

Currently, the action does not support this.

### Suggested solution

Ideas:

1. Support text and "contained-in". In this case, I configure "assign this issue to me" as text to recognize
2. Support OpenAI API to use an LLM to evaluate if text is an "assign-me" wish: IN: text OUT: "yes" or "no".

In case the LLM approach is used, there should be no comment and action if the issue is already taken. (To avoid errors)

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

### LINKED ISSUE #247: Feature: Add action output to indicate if something happened
### Type of feature

💡 Feature

### Current behavior

We have workflows running reacting on set labels.

If a GitHub action assigns a label, no workflow is run

image

### Suggested solution

Thus, I need a way to run another step if someone was assigned.

Draft: I would like to have `if steps.assign.outputs.assigned == "yes"` as condition for my next step. I would just use the same steps as when the label was manually assigned

https://github.com/JabRef/jabref/blob/25635de59496e2765ccfab19c07e91b6c48067a4/.github/workflows/on-labeled-issue.yml#L49

(This wish is similar to https://github.com/bdougie/take-action/issues/27 for the [take-action](https://github.com/bdougie/take-action)).

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

### LINKED ISSUE #248: Feature: Be more strict in parsing
### Type of feature

💡 Feature

### Current behavior

If the trigger appears anywhere in the text, the action is triggered:

image

### Suggested solution

Only listen if the command is the single command in the comment.

See https://github.com/microsoft/winget-pkgs/pull/173505#issuecomment-2351583871 for commands in other projects.

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by takanome-dev**
## What type of PR is this? (check all applicable)

- [x] 💡 Feature
- [ ] 🐛 Bug Fix
- [x] 📝 Documentation Update
- [ ] 🎨 Style
- [x] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] ⏩ Revert

## Description

This pr adds new commands to the action.

## Features

- `/assign @<user>` & `/unassign @<user>` commands used by maintainers to assign and unassign issues to contributors
- `/assign-me` & `/unassign-me` commands are for contributors wanting to take on an issue
- post a comment if the commenter shows interest in contributing

## Related Tickets & Documents

- fixes #248 
- fixes #247 
- fixes #244 
- fixes #240
- fixes #241
- fixes #246

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by koppor** [comment]
I tested the branch. 

Output of GitHub:

> The following actions use a deprecated Node.js version and will be forced to run on node20: takanome-dev/assign-issue-action@refactor-rewrite-action. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/

The new placeholders don't seem to work:

image

> `Note that you will be unassigned if it isn't closed within **{{ total_days }} days** (**{{ unassigned_date }}**)` 
> `A maintainer can also add the **{{ pin_label }}** label to prevent it from being unassigned automatically.`

**Comment by koppor** [comment]
Oh, the action assigned me 🤣

image

**Comment by takanome-dev** [comment]
I failed making it work on the first try 🤣🤣  Well, thanks for testing this out.

I still have failing tests that needs to be fixed that's why I haven't tested this yet on my `test-action-repo`.

Will try to make it work tomorrow morning 🙃

**Comment by koppor** [comment]
Tested [`5631f93` (#245)](https://github.com/takanome-dev/assign-issue-action/pull/245/commits/5631f9391f376581c151aba033633656d5b8f2d3)

- ✅ assignment works
-❌ placeholder in comment are not replaced
- ✅ output was `yes`

image

**Comment by takanome-dev** [comment]
It will work if this pr is merged and I'm working on it. Just needs to do some final testing and update the readme

**Comment by koppor** [comment]
> It will work if this pr is merged and I'm working on it. Just needs to do some final testing and update the readme

I am just impatient 😅🤣🤣

**Comment by takanome-dev** [comment]
Thanks so much @koppor for all the issues you opened this week and for your patience throughout the process. Your detailed descriptions were incredibly helpful! It made me really happy to work on this again after 2 years 😊 

If you encounter any more issues or have ideas for new features within the action, don’t hesitate to open more issues. Your contributions are greatly appreciated! 🙌

**Pull request merged**
